name: challenger_env
channels:
  - pytorch
  - anaconda
  - conda-forge
  - bioconda
  - soumith
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aiohttp=3.9.5=py311h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - annotated-types=0.6.0=py311h06a4308_0
  - anyio=4.2.0=py311h06a4308_0
  - aom=3.6.0=h6a678d5_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py311h5eee18b_0
  - arrow=1.3.0=py311h06a4308_0
  - arrow-cpp=16.1.0=hc1eb8f0_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py311h06a4308_0
  - attrs=23.1.0=py311h06a4308_0
  - aws-c-auth=0.6.19=h5eee18b_0
  - aws-c-cal=0.5.20=hdbd6064_0
  - aws-c-common=0.8.5=h5eee18b_0
  - aws-c-compression=0.2.16=h5eee18b_0
  - aws-c-event-stream=0.2.15=h6a678d5_0
  - aws-c-http=0.6.25=h5eee18b_0
  - aws-c-io=0.13.10=h5eee18b_0
  - aws-c-mqtt=0.7.13=h5eee18b_0
  - aws-c-s3=0.1.51=hdbd6064_0
  - aws-c-sdkutils=0.1.6=h5eee18b_0
  - aws-checksums=0.1.13=h5eee18b_0
  - aws-crt-cpp=0.18.16=h6a678d5_0
  - aws-sdk-cpp=1.10.55=h721c034_0
  - babel=2.11.0=py311h06a4308_0
  - beautifulsoup4=4.12.3=py311h06a4308_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - boost-cpp=1.82.0=hdb19cb5_2
  - boto3=1.40.50=pyhd8ed1ab_0
  - botocore=1.40.50=pyhd8ed1ab_0
  - bottleneck=1.3.7=py311hf4808d0_0
  - brotli=1.0.9=h5eee18b_8
  - brotli-bin=1.0.9=h5eee18b_8
  - brotli-python=1.0.9=py311h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.16.0=hb05425b_5
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=1.16.0=py311h5eee18b_1
  - chardet=4.0.0=py311h06a4308_1003
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.7=py311h06a4308_0
  - comm=0.2.1=py311h06a4308_0
  - contourpy=1.2.0=py311hdb19cb5_0
  - cookiecutter=2.6.0=py311h06a4308_0
  - cpython=3.11.13=py311hd8ed1ab_0
  - cuda-cudart=12.4.99=hd3aeb46_0
  - cuda-cudart_linux-64=12.4.99=h59595ed_0
  - cuda-cupti=12.4.127=h6a678d5_1
  - cuda-libraries=12.4.0=ha770c72_0
  - cuda-nvrtc=12.4.99=hd3aeb46_0
  - cuda-nvtx=12.4.127=h6a678d5_1
  - cuda-opencl=12.4.99=h59595ed_0
  - cuda-runtime=12.4.0=ha804496_0
  - cuda-version=12.4=hbda6634_3
  - curl=8.7.1=hdbd6064_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - datasets=2.19.1=py311h06a4308_0
  - dav1d=1.2.1=h5eee18b_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.6.7=py311h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - dill=0.3.8=py311h06a4308_0
  - docker-pycreds=0.4.0=pyhd3eb1b0_0
  - einops=0.8.1=pyhd8ed1ab_0
  - et_xmlfile=2.0.0=py311h06a4308_0
  - eval_type_backport=0.2.2=pyha770c72_0
  - evaluate=0.4.3=py311h107ce05_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.4=h6a678d5_0
  - ffmpeg=4.2.2=h20bf706_0
  - filelock=3.13.1=py311h06a4308_0
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.51.0=py311h5eee18b_0
  - freetype=2.13.3=h4a9f257_0
  - frozenlist=1.4.0=py311h5eee18b_0
  - fsspec=2024.3.1=py311h06a4308_0
  - gflags=2.2.2=h6a678d5_1
  - giflib=5.2.1=h5eee18b_3
  - gitdb=4.0.7=pyhd3eb1b0_0
  - gitpython=3.1.43=py311h06a4308_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - glog=0.5.0=h6a678d5_1
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py311hc9b5ff0_0
  - gnutls=3.6.15=he1e5248_0
  - graphite2=1.3.14=h295c915_1
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - h11=0.14.0=py311h06a4308_0
  - harfbuzz=4.3.0=hf52aaf7_2
  - hf-xet=1.1.6=py39h598437d_0
  - httpcore=1.0.2=py311h06a4308_0
  - httpx=0.27.0=py311h06a4308_0
  - huggingface_hub=0.35.3=pyhd8ed1ab_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py311h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.28.0=py311h06a4308_0
  - ipython=8.27.0=py311h06a4308_0
  - ipywidgets=8.1.2=py311h06a4308_0
  - jedi=0.19.1=py311h06a4308_0
  - jinja2=3.1.4=py311h06a4308_0
  - jmespath=1.0.1=py311h06a4308_0
  - joblib=1.4.2=py311h06a4308_0
  - jpeg=9e=h5eee18b_3
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.19.2=py311h06a4308_0
  - jsonschema-specifications=2023.7.1=py311h06a4308_0
  - jupyter=1.0.0=py311h06a4308_9
  - jupyter-lsp=2.2.0=py311h06a4308_0
  - jupyter_client=8.6.0=py311h06a4308_0
  - jupyter_console=6.6.3=py311h06a4308_0
  - jupyter_core=5.7.2=py311h06a4308_0
  - jupyter_events=0.10.0=py311h06a4308_0
  - jupyter_server=2.14.1=py311h06a4308_0
  - jupyter_server_terminals=0.4.4=py311h06a4308_1
  - jupyterlab=4.2.5=py311h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.27.3=py311h06a4308_0
  - jupyterlab_widgets=3.0.10=py311h06a4308_0
  - kiwisolver=1.4.4=py311h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.38=h1181459_1
  - leptonica=1.82.0=h42c8aad_2
  - lerc=3.0=h295c915_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libarchive=3.6.2=hfab0078_4
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcublas=12.4.2.65=hd3aeb46_0
  - libcufft=11.2.0.44=hd3aeb46_0
  - libcufile=1.9.0.20=hd3aeb46_0
  - libcups=2.4.2=h2d74bed_1
  - libcurand=10.3.5.119=hd3aeb46_0
  - libcurl=8.7.1=h251f7ec_0
  - libcusolver=11.6.0.99=hd3aeb46_0
  - libcusparse=12.3.0.142=hd3aeb46_0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=14.2.0=h77fa898_1
  - libgrpc=1.62.2=h2d74bed_0
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libllvm14=14.0.6=hdb19cb5_3
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=12.2.5.2=hd3aeb46_0
  - libnvfatbin=12.4.99=hd3aeb46_0
  - libnvjitlink=12.4.99=hd3aeb46_0
  - libnvjpeg=12.3.1.89=h59595ed_0
  - libogg=1.3.5=h27cfd23_1
  - libopenblas=0.3.21=h043d6bf_0
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - libprotobuf=4.25.3=he621ea3_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtheora=1.1.1=h7f8727e_3
  - libthrift=0.15.0=h1795dd8_2
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h097e994_2
  - libxml2=2.13.5=hfdd30dd_0
  - libxslt=1.1.41=h097e994_0
  - libzlib=1.2.13=h4ab18f5_6
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markdown-it-py=2.2.0=py311h06a4308_1
  - markupsafe=2.1.3=py311h5eee18b_0
  - matplotlib=3.10.6=py311h38be061_1
  - matplotlib-base=3.10.6=py311h71dd3da_0
  - matplotlib-inline=0.1.6=py311h06a4308_0
  - mdurl=0.1.0=py311h06a4308_0
  - minizip=4.0.3=hf59b114_0
  - mistune=2.0.4=py311h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.8=py311h5eee18b_0
  - mkl_random=1.2.4=py311hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py311h06a4308_0
  - multidict=6.0.4=py311h5eee18b_0
  - multiprocess=0.70.15=py311h06a4308_0
  - mysql=8.4.0=h29a9f33_1
  - nbclient=0.8.0=py311h06a4308_0
  - nbconvert=7.10.0=py311h06a4308_0
  - nbformat=5.9.2=py311h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py311h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.3=py311h06a4308_0
  - notebook=7.2.2=py311h06a4308_0
  - notebook-shim=0.2.3=py311h06a4308_0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numexpr=2.8.7=py311h65dcdc2_0
  - numpy=1.26.4=py311h08b1b3b_0
  - numpy-base=1.26.4=py311hf175353_0
  - ocl-icd=2.3.2=h5eee18b_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openpyxl=3.1.5=py311h534898f_2
  - openssl=3.6.0=h26f9b46_0
  - orc=2.0.1=h2d29ad5_0
  - overrides=7.4.0=py311h06a4308_0
  - packaging=24.1=py311h06a4308_0
  - pandas=2.2.2=py311ha02d727_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pathtools=0.1.2=pyhd3eb1b0_1
  - patsy=1.0.1=py311h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pillow=10.4.0=py311h5eee18b_0
  - pip=24.2=py311h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - platformdirs=3.10.0=py311h06a4308_0
  - ply=3.11=py311h06a4308_0
  - prometheus_client=0.14.1=py311h06a4308_0
  - prompt-toolkit=3.0.43=py311h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - protobuf=4.25.3=py311h12ddb61_0
  - psutil=5.9.0=py311h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyarrow=16.1.0=py311ha02d727_0
  - pybind11-abi=4=hd3eb1b0_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=2.8.2=py311h06a4308_0
  - pydantic-core=2.20.1=py311hb02cf49_0
  - pygments=2.15.1=py311h06a4308_1
  - pyparsing=3.1.2=py311h06a4308_0
  - pyqt=6.7.1=py311h6a678d5_0
  - pyqt5-sip=12.13.0=py311h5eee18b_0
  - pyqt6-sip=13.9.1=py311h5eee18b_0
  - pyside6=6.7.2=py311hfe62871_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.9=h955ad1f_0
  - python-dateutil=2.9.0post0=py311h06a4308_2
  - python-fastjsonschema=2.16.2=py311h06a4308_0
  - python-gil=3.11.13=hd8ed1ab_0
  - python-json-logger=2.0.7=py311h06a4308_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python-xxhash=2.0.2=py311h5eee18b_1
  - python_abi=3.11=2_cp311
  - pytorch=2.5.1=py3.11_cuda12.4_cudnn9.1.0_0
  - pytorch-cuda=12.4=hc786d27_6
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py311h06a4308_0
  - pyyaml=6.0.1=py311h5eee18b_0
  - pyzmq=25.1.2=py311h6a678d5_0
  - qhull=2020.2=hdb19cb5_2
  - qt-main=6.7.2=h06a4308_0
  - qt5compat=6.7.2=h0902c3e_0
  - qtbase=6.7.2=hdaa5aa8_0
  - qtconsole=5.5.1=py311h06a4308_0
  - qtdeclarative=6.7.2=h6a678d5_0
  - qtimageformats=6.7.2=h7fa0f6f_0
  - qtpy=2.4.1=py311h06a4308_0
  - qtshadertools=6.7.2=h6a678d5_0
  - qtsvg=6.7.2=he621ea3_0
  - qttools=6.7.2=h80c7b02_0
  - qttranslations=6.7.2=h6a678d5_0
  - qtwebchannel=6.7.2=h6a678d5_0
  - qtwebengine=6.7.2=hcbda680_0
  - qtwebsockets=6.7.2=h6a678d5_0
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=py311h06a4308_0
  - regex=2024.9.11=py311h5eee18b_0
  - requests=2.32.3=py311h06a4308_0
  - responses=0.13.3=pyhd3eb1b0_0
  - rfc3339-validator=0.1.4=py311h06a4308_0
  - rfc3986-validator=0.1.1=py311h06a4308_0
  - rich=13.7.1=py311h06a4308_0
  - rpds-py=0.10.6=py311hb02cf49_0
  - s2n=1.3.27=hdbd6064_0
  - s3transfer=0.14.0=pyhd8ed1ab_0
  - safetensors=0.4.2=py311h24d97f6_1
  - samtools=1.6=hc3601fc_10
  - scikit-learn=1.7.2=py311h505adc9_0
  - scipy=1.13.1=py311h08b1b3b_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - send2trash=1.8.2=py311h06a4308_0
  - sentry-sdk=2.18.0=pyhd8ed1ab_0
  - setproctitle=1.2.2=py311h5eee18b_0
  - setuptools=72.1.0=py311h06a4308_0
  - sip=6.10.0=py311h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - smmap=4.0.0=pyhd3eb1b0_0
  - snappy=1.2.1=h6a678d5_0
  - sniffio=1.3.0=py311h06a4308_0
  - soupsieve=2.5=py311h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.14.5=py311h76ea63d_0
  - tbb=2021.8.0=hdb19cb5_0
  - terminado=0.17.1=py311h06a4308_0
  - tesseract=5.2.0=h6a678d5_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - threadpoolctl=3.5.0=py311h92b7b1e_0
  - tinycss2=1.2.1=py311h06a4308_0
  - tk=8.6.14=h39e8969_0
  - tokenizers=0.21.0=py311h182c674_0
  - torchtriton=3.1.0=py311
  - torchvision=0.20.1=py311_cu124
  - tornado=6.4.1=py311h5eee18b_0
  - tqdm=4.66.4=py311h92b7b1e_0
  - traitlets=5.14.3=py311h06a4308_0
  - transformers=4.49.0=pyhd8ed1ab_0
  - typing=3.10.0.0=py311h06a4308_0
  - typing-extensions=4.11.0=py311h06a4308_0
  - typing_extensions=4.11.0=py311h06a4308_0
  - tzdata=2024a=h04d1e81_0
  - unicodedata2=15.1.0=py311h5eee18b_0
  - unidecode=1.3.8=py311h06a4308_0
  - urllib3=2.2.2=py311h06a4308_0
  - utf8proc=2.6.1=h5eee18b_1
  - wandb=0.22.2=py311hcc66767_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py311h06a4308_1
  - websocket-client=1.8.0=py311h06a4308_0
  - wheel=0.43.0=py311h06a4308_0
  - widgetsnbextension=4.0.10=py311h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xcb-util-cursor=0.1.4=h5eee18b_0
  - xxhash=0.8.0=h7f8727e_3
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.9.3=py311h5eee18b_0
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.5=hc292b87_2
  - pip:
      - accelerate==0.33.0
      - hyper-connections==0.2.1
      - local-attention==1.11.2
      - sympy==1.13.1
